# Generated by Django 5.2.11 on 2026-02-17 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField(max_length=20)),
                ('contact_address', models.TextField()),
                ('education_qualification', models.CharField(max_length=255)),
                ('graduation_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2031)])),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('skills', models.TextField(help_text='Comma-separated list of skills/technologies (e.g. Python, Django, React)')),
                ('resume_file', models.FileField(help_text='Upload PDF, DOC, or DOCX only', upload_to='resumes/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
